### ISSUE TITLE
"Share" feature reported not working on iOS

### ISSUE THREAD

**Issue by aaronfay** [roedoejet/AnyLanguage-Wordle#11]
Testing on this wordle (https://nishnaabemwin.anywordle.net/) the "Share" button does not seem to work on iOS devices, reported by two users. I can verify this on my iPad that the share doesn't appear to do anything. Android seems fine.

Today's word for testing is "gaasin".

I can also confirm that "Share" works on iOS (same iPad) on the nêhiyaw Wordle (wordle.kiyanaw.net) so it must be some change introduced since that time.

**Comment by roedoejet** [comment]
do you have the commit sha handy for where you forked the nêhiyaw Wordle from?

**Comment by roedoejet** [comment]
All I can think is that it's maybe some weird interaction with this: https://github.com/roedoejet/AnyLanguage-Wordle/pull/8

I don't have an iPhone so it's proving a bit difficult to debug as it's working on all my devices. What browser is this happening in? Could it be related to using a Facebook browser or something (see https://github.com/cwackerfuss/react-wordle/pull/233#issuecomment-1046233574)

**Comment by aaronfay** [comment]
Safari browser on iPad, I can actually see the same behavior on Safari browser on my desktop 🤔  though I don't see any errors in the console

**Comment by roedoejet** [comment]
OK - on Safari Version 14.1.2 (16611.3.10.1.6) on my Mac running Big Sur the share button works at https://nishnaabemwin.anywordle.net/ in that the text is copied to my clipboard, but I think the issue from #12 is preventing the toast from appearing. Is the text copied to the clipboard and the toast just doesn't appear, or it's also not copying to the clipboard?

**Comment by roedoejet** [comment]
Because with #12 fixed, that might solve the problem?

**Comment by aaronfay** [comment]
Okay yes, that actually looks to be the case. The text does appear to be copying for me on both my iPad and desktop. I'll pull those changes in #12 and roll them out to see if that clears things up

**Comment by roedoejet** [comment]
awesome - that would be a nice 2 for 1 :) I'll hang on to close this until you can confirm. Thanks for bringing this up!

**Comment by aaronfay** [comment]
Fixed, thank you 🙏🏻

**Comment by howard-haowen** [comment]
My app is also having the same problem. I tried it on iPhone and Mac, and the text was not even copied to my clipboard. Several uses of my app have also reported to me that the Share function fails to work (though it used to work before I merged Aidan's recent update on customizing instruction tab, language display names, and all that. The sha number is 4debfa10336c007b6403eec9c6114deed3663e24), but I don't know what kind of OS systems they use. 

Here's my repo: https://github.com/howard-haowen/paiwan-wordle
Here's my app: http://howard-haowen.rohan.tw/paiwan-wordle/

**Comment by roedoejet** [comment]
Hi @howard-haowen - I think this is related to an issue with https - the clipboard doesn't work with http - I believe it's a security issue enforced by the browse. I just tested and while http://howard-haowen.rohan.tw/paiwan-wordle/ does not work https://howard-haowen.rohan.tw/paiwan-wordle/ does work. I recommend forcing https: https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https let me know if you still have problems after doing that

**Comment by howard-haowen** [comment]
@roedoejet , thanks for taking time to test it out!  😃  Forcing HTTP did solve the problem!  👍
